### ISSUE TITLE
Initialise the database fails on redhat

### ISSUE THREAD

**Issue by vamsikt** [geerlingguy/ansible-role-postgresql#107]
When checking the PostgreSQL database is initialized state, initialize script failing with initdb not found
 
https://github.com/geerlingguy/ansible-role-postgresql/blob/master/tasks/initialize.yml#L23

`"cmd": "/usr/bin/initdb -D /var/lib/pgsql/data", "msg": "[Errno 2] No such file or directory",`

**Comment by proffalken** [comment]
Hi, did you find a resolution to this? I'm seeing my ansible runs just hang at this stage when running from Packer:

```
    digitalocean: TASK [geerlingguy.postgresql : Ensure PostgreSQL database is initialized.] *****

```

**Comment by vamsikt** [comment]
I upgraded the Postgres version and did not encounter this issue.

**Comment by grossedouceur** [comment]
I don't think this issue is resolved.

For instance, for PostgreSQL 13, one need to run this command to initialise the database.

    sudo /usr/pgsql-13/bin/postgresql-13-setup initdb

But this role tries to run the following command.

     /usr/bin/initdb -D /var/lib/pgsql/13/data

Since `/usr/bin/initdb` doesn't exist, that command cannot work.

A potential solution would be to define the whole init command as a variable.
