### ISSUE TITLE
Centos6 : failed to start due to default parameter

### ISSUE THREAD

**Issue by roumano** [geerlingguy/ansible-role-postgresql#13]
i'm using the roles without any specific parametres. 

postgres refuse to start on Centos6 (it's starting on other OS)
the module don't give me information about the issue : 
```
TASK [geerlingguy.postgresql : Ensure PostgreSQL is started and enabled on boot.] ***
fatal: [centos6]: FAILED! => {"changed": false, "failed": true, "msg": "Starting postgresql service: [FAILED]\r\n"}
```
Debuging manually the issue give me the error : 
```
runuser -l postgres -c '/usr/bin/postmaster -p 5432 -D /var/lib/pgsql/data'
FATAL:  unrecognized configuration parameter "unix_socket_directories"
```
remove the parameter is working : 
```
diff /var/lib/pgsql/data/postgresql.conf /var/lib/pgsql/data/postgresql.conf.old
502c502
< #unix_socket_directories = '/var/run/postgresql'
---
> unix_socket_directories = '/var/run/postgresql'
[root@centos6 ~]# /etc/init.d/postgresql start
Démarrage du service postgresql :                          [  OK  ]
[root@centos6 ~]# /etc/init.d/postgresql status
postmaster (pid  9089) en cours d'exécution...
```

can you remove this new option on old OS/ old postgres version ? 

```
[root@centos6 ~]# rpm -qa |grep gres
postgresql-server-8.4.20-7.el6.x86_64
postgresql-8.4.20-7.el6.x86_64
postgresql-contrib-8.4.20-7.el6.x86_64
postgresql-libs-8.4.20-7.el6.x86_64
```

**Comment by geerlingguy** [comment]
@roumano - You can override a variable (https://github.com/geerlingguy/ansible-role-postgresql/blob/d7954de61a37e97a8767387dd9550cf7c5ffc78e/defaults/main.yml#L12) to prevent that option from being set. In your playbook's variables, just add:

```yaml
postgresql_global_config_options: []
```

**Comment by roumano** [comment]
Hi,
I known i can overwrite variable
but the roles must run "out of the box" otherwise you need to remove OL6 of
the supported list ...

2017-04-20 18:57 GMT+02:00 Jeff Geerling <notifications@github.com>:

**Comment by geerlingguy** [comment]
@roumano - For legacy/old OSes, it should be expected that you'd need to set a few variables for them specifically. I have a lot of roles that support CentOS 6/7, Fedora 23/24/25, Ubuntu 12/14/16, Debian 7/8, etc.—if I made it so every role ran out of the box on all the supported OSes, it would add a _huge_ amount of technical debt which I am not willing to take on.

Rather, I allow (as in this case) for slight variation so that the role works on legacy infrastructure (at least for most of the duration of community support for the OS—CentOS/RHEL releases seem to linger forever... I still get some people asking for RHEL 4 or 5 support from time to time!).
