### ISSUE TITLE
Cannot use Python3 with Ubuntu20.04LTS

### ISSUE THREAD

**Issue by alutsky** [geerlingguy/ansible-role-postgresql#154]
Python3 version required by this role is <3.7;
Python3 version that supports Ubuntu20.04 is >3.7 at least, perhaps even >3.8
As such when trying to use This Role + Python3 + Ubuntu20.04:  Ansible cannot satisfy dependencies

**Comment by jeanmonet** [comment]
Huh you might have confused something? AFAIK Python is relevant in this role only with respect to the database driver (psycopg2 -> for python 2 or for python 3). Otherwise Python is relevant with respect to Ansible itself, and does not affect the role.
Your problem seems related to your general configuration and not probably an issue to be opened here.
