### ISSUE TITLE
Annoying chicken-and-egg problem from PR 15

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-postgresql#16]
https://github.com/geerlingguy/ansible-role-postgresql/pull/15 introduced a swap to the order of creating databases and users.

The way it was originally, databases would be created first, then user accounts which could have privileges for those databases.

This swap caused a breaking change for any playbooks relying on that ordering, because you could create a generic database, then add users that have privileges on that database. With the change, it doesn't always work as cleanly to create generic users, then assign ownership using that user to a particular database.

Therefore I'm going to revert that change and bump the minor version again in favor of the original order (which is also the convention I use for my MySQL role, so it's more consistent that way).

**Comment by mcayland** [comment]
After a bit of investigation it appears that this commit breaks our playbook sample below:

postgresql_users:
  - name: pguser
    password: "pgpassword"
    port: 5432

postgresql_databases:
  - name: appdb
    encoding: UTF-8
    port: 5432
    owner: pguser

Here we are trying to create a specific PostgreSQL user pguser for our application and then give that user full ownership rights on our application database. However the playbook fails on "Ensure PostgreSQL databases are present" with the error "Database query failed: role \"pguser\" does not exist\n" since the user hasn't been created first.

Note that in PostgreSQL users are cluster-wide rather than specific to one particular database which might be adding to the confusion.
