### ISSUE TITLE
Check for sudo dependency

### ISSUE THREAD

**Issue by 1977er** [geerlingguy/ansible-role-postgresql#62]
When you run this role (on a Debian9) with no `sudo` package installed, you run into the following error message:

> TASK [geerlingguy.postgresql : Ensure PostgreSQL users are present.]
> [...]
> MSG:
> 
> MODULE FAILURE
> See stdout/stderr for the exact error
> 
> MODULE_STDERR:
> 
> /bin/sh: 1: sudo: not found

(assuming you set `no_log: false`)

**Comment by kolewu** [comment]
This is a general ansible problem. If *become* is used, *sudo* is needed.

Unfortunately there seems to be no check for the remote host to ensure that all needed packages are installed. That's also true for python.

So in general you have to make sure, that all ansible requirements are fulfilled on all remote hosts. The same is (was?) true for *aptitude* on debian that is used by the *apt* module (nowadays since ansible 2.4 *apt-get* will be used if *aptitude* is not available).
