### ISSUE TITLE
add support for windows and mac

### ISSUE THREAD

**Issue by shaiatias** [geerlingguy/ansible-role-postgresql#75]
not sure this is a common case, but still.
as part of my setup - i need to configure postgres on multiple os types.

installation is pretty simple but the configuration process is cumbersome.
it would help a lot if you would add support for windows and mac.

**Comment by geerlingguy** [comment]
Sorry, but at this time I don't typically support Windows or Mac on any of my Linux-focused roles. If I do need to add support for those platforms, I usually create a separate role. You can usually install Postgres on Windows via Chocolatey, or on Mac via brew, but 99.9% of the time I'll still do it on a VM or Docker image running Linux because that's the most reliable way to run Postgres (IMHO).
